version: '3.9'

services:
  bdd1:
    image: postgres:12
    container_name: bdd1
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${MY_USER}
      POSTGRES_PASSWORD: ${MY_PASSWORD}
      POSTGRES_DB: ${MY_DB1}
    ports:
      - "5432:5432"

  bdd2:
    image: postgres:12
    container_name: bdd2
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${MY_USER}
      POSTGRES_PASSWORD: ${MY_PASSWORD}
      POSTGRES_DB: ${MY_DB2}
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@mail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8888:80"
